apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comet-admin.fullname" . }}
  labels:
    {{- include "comet-admin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "comet-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "comet-admin.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret -}}
      imagePullSecrets:
        - name: {{ include "comet-admin.fullname" . }}-image-pull-secret
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.hash }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "{{ .Values.nodeEnv }}"
            - name: NPM_RUN
              value: "{{ .Values.npmRun }}"
            - name: TZ
              value: "{{ .Values.timeZone }}"
            - name: API_URL
              value: https://{{ .Values.api.domain }}{{ .Values.api.basePath }}
            - name: ADMIN_URL
              value: https://{{ .Values.domain }}
            {{- if .Values.sitesConfig }}
            - name: SITES_CONFIG
              value: '{{- toJson .Values.sitesConfig }}'
            {{- end }}
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /status/health
              port: http
          readinessProbe:
            httpGet:
              path: /status/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
