{{- if .Values.prelogin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comet-site.fullname" . }}-prelogin
  labels:
    {{- include "comet-site.prelogin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prelogin.service.type }}
  ports:
    - port: {{ .Values.prelogin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "comet-site.prelogin.selectorLabels" . | nindent 4 }}
{{- end }}
