{{- if .Values.generateSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comet-api.fullname" . }}
  labels:
    {{- include "comet-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  IMGPROXY_KEY: "{{ .Values.imgproxy.key }}"
  IMGPROXY_SALT: "{{ .Values.imgproxy.salt }}"
  POSTGRESQL_PWD: "{{ .Values.postgresql.password | b64enc }}"
  BASIC_AUTH_PASSWORD: "{{ .Values.basicAuthPassword }}"
  DAM_SECRET: "{{ .Values.dam.secret }}"
  {{- if eq .Values.blobStorage.driver "azure" }}
  AZURE_ACCOUNT_KEY: "{{ .Values.blobStorage.azure.key }}"
  {{- else if eq .Values.blobStorage.driver "s3" }}
  S3_SECRET_ACCESS_KEY: "{{ .Values.blobStorage.s3.secretAccessKey }}"
  {{- end }}
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
