{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comet-site-preview.fullname" . }}
  labels:
    {{- include "comet-site-preview.labels" . | nindent 8 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
