# Default values for site.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: {}
secrets: {}

replicaCount: 1

image:
  repository: ""
  hash: ""
  pullPolicy: IfNotPresent
  pullSecret: "" # will be overwritten by CI

npmRun: "serve"

securityContext:
  runAsNonRoot: true                # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-22
  runAsUser: 10001                  # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-37
  seccompProfile:
    type: RuntimeDefault            # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-29
  capabilities:
    drop:
    - NET_RAW                       # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-27
    - ALL                           # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-34
  readOnlyRootFilesystem: true      # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-21

autoMountServiceAccountToken: false # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-35

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    memory: 200Mi
    cpu: 1
  requests:
    cpu: 50m
    memory: 200Mi

route:
  enabled: false

ingress:
  enabled: false

hosts: []

cdn:
  enabled: false
  originHeader: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

api:
  basePath: "/api"

admin:
  domain: ""
