# Default values for site.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: {}
secrets: {}

replicaCount: 1

image:
  repository: ""
  hash: ""
  pullPolicy: IfNotPresent
  pullSecret: "" # will be overwritten by CI

npmRun: "serve"

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    memory: 400Mi
    cpu: 1
  requests:
    cpu: 50m
    memory: 200Mi

autoMountServiceAccountToken: true

route:
  enabled: false

ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"

hosts: []

cdn:
  enabled: false
  originHeader: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

api:
  basePath: "/api"

admin:
  domain: ""
