apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "comet-site.fullname" . }}
  labels:
    {{- include "comet-site.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "comet-site.fullname" . }}-rb
  labels:
    {{- include "comet-site.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ include "comet-site.fullname" . }}
