nodeEnv: production
npmRun: serve
timeZone: Europe/Vienna

replicaCount: 1

image:
  repository: nginx
  hash: ""
  pullPolicy: IfNotPresent
  pullSecret: "" # will be overwritten by CI

api:
  basePath: "/api"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true                # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-22
  runAsUser: 10001                  # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-37
  seccompProfile:
    type: RuntimeDefault            # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-29
  capabilities:
    drop:
    - NET_RAW                       # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-27
    - ALL                           # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-34
  readOnlyRootFilesystem: true      # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-21

autoMountServiceAccountToken: false # https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-35

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

route:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

cdn:
  enabled: false
  originHeader: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
