nodeEnv: production
npmRun: serve
timeZone: Europe/Vienna

replicaCount: 1

image:
  repository: nginx
  hash: "" # will be used, if tag is not set
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: "" # will be overwritten by CI

api:
  basePath: "/api"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

route:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

cdn:
  enabled: false
  originHeader: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
