env:
  NODE_ENV: "production"
  TZ: "Europe/Vienna"
additionalConfigMapNames: []
secrets: {}
additionalSecretNames: []
additionalPodLabels: {}

replicaCount: 2

image:
  repository: ""
  hash: "" # will be used, if tag is not set
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: "" # will be overwritten by CI

npmRun: "serve"

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    memory: 200Mi
    cpu: 1
  requests:
    cpu: 50m
    memory: 200Mi

initContainer:
  resources:
    limits:
      memory: 512Mi
      cpu: 1
    requests:
      cpu: 50m
      memory: 512Mi

livenessProbe: 
  path: "/site/api/status"

readinessProbe:
  path: "/site/api/status"

autoMountServiceAccountToken: true
