{{- range $name, $job := .Values.cronJobs }}
{{- with $ -}}
{{- if or $job.enabled (not (hasKey $job "enabled")) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ print (include "comet-api.fullname" .) "-" $name | trunc 52 | trimSuffix "-" }}
  labels:
    comet-dxp.com/instance: "{{ .Release.Name }}"
    {{- include "comet-api.labels" . | nindent 4 }}
    {{- if $job.additionalLabels }}
      {{- tpl ($job.additionalLabels | toYaml) . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit | default 2 }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit | default 2 }}
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Forbid" }}
  startingDeadlineSeconds: {{ $job.startingDeadlineSeconds | default 120 }}
  jobTemplate:
    metadata:
      annotations:
        comet-dxp.com/trigger: "cronjob"
      labels:
        comet-dxp.com/instance: "{{ .Release.Name }}"
        comet-dxp.com/parent-cron-job: {{ print (include "comet-api.fullname" .) "-" $name | trunc 52 | trimSuffix "-" }}
    spec:
      backoffLimit: {{ $job.backoffLimit | default 1 }}
      activeDeadlineSeconds: {{ $job.activeDeadlineSeconds | default 600 }}
      ttlSecondsAfterFinished: {{ $job.ttlSecondsAfterFinished | default 604800 }}
      template:
        spec:
          {{- if .Values.image.pullSecret -}}
          imagePullSecrets:
            - name: {{ include "comet-api.fullname" . }}-image-pull-secret
          {{- end }}
          restartPolicy: {{ $job.restartPolicy | default "Never" }}
          serviceAccountName: {{ include "comet-api.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}-cronjob-{{ $name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}@{{ .Values.image.hash }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["bash", "-c", {{ $job.command }}]
              envFrom:
                - configMapRef:
                    name: {{ include "comet-api.fullname" . }}
                - secretRef:
                    name: {{ include "comet-api.fullname" . }}
              resources:
                {{- $job.resources | default .Values.resources | toYaml | nindent 16 }}
---
{{- end }}
{{- end }}
{{- end -}}
