apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comet-api.fullname" . }}-image-pull-secret
  labels:
    {{- include "comet-api.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ required "Missing image.pullSecret" .Values.image.pullSecret }}
type: kubernetes.io/dockerconfigjson
