{{- if .Values.prelogin.enabled -}}
{{- if .Values.prelogin.generateSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comet-site.fullname" . }}-prelogin
  labels:
    {{- include "comet-site.prelogin.labels" . | nindent 8 }}
type: Opaque
stringData:
  IDP_CLIENT_SECRET: {{ .Values.prelogin.idp.clientSecret | quote }}
  NEXTAUTH_SECRET: {{ .Values.prelogin.idp.clientSecret | quote }}
{{- end }}
{{- end }}
