timeZone: Europe/Vienna

domain: ""
ingress:
  enabled: false
route:
  enabled: false

oauth2-proxy:
  extraArgs:
    api-route: /api
    code-challenge-method: S256
    pass-authorization-header: true
    pass-access-token: true
    cookie-secure: true
    cookie-samesite: lax
    cookie-httponly: true
    skip-provider-button: true
    silence-ping-logging: true
    request-logging: false
    auth-logging: false
    standard-logging: true
    cookie-refresh: 55m
  config:
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "file:///dev/null" ]
      skip_auth_routes = [ "^/status/" ]
  resources:
    limits:
      cpu: 1
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 64Mi
  service:
    portNumber: 3000
