apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comet-site.fullname" . }}
  labels:
    {{- include "comet-site.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "comet-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "comet-site.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret -}}
      imagePullSecrets:
        - name: {{ include "comet-site.fullname" . }}-image-pull-secret
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.hash }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "comet-site.fullname" . }}
            - secretRef:
                name: {{ include "comet-site.fullname" . }}
          env:
            - name: NPM_RUN
              value: "{{ .Values.npmRun }}"
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
              httpHeaders:
              - name: x-cdn-origin-check
                value: "{{ .Values.cdn.originHeader }}"
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
              httpHeaders:
              - name: x-cdn-origin-check
                value: "{{ .Values.cdn.originHeader }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
