apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comet-site.fullname" . }}
  labels:
    {{- include "comet-site.labels" . | nindent 8 }}
type: Opaque
stringData:
  API_PASSWORD: {{ .Values.api.basicAuthPassword | quote }}
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}