{{- if .Values.builder.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "comet-site.fullname" . }}-build
  labels:
    comet-dxp.com/builder: "true"
    comet-dxp.com/instance: "{{ .Release.Name }}"
    {{- include "comet-site.labels" . | nindent 4 }}
  annotations:
    comet-dxp.com/content-scope: '{{- toJson .Values.contentScope }}'
    comet-dxp.com/label: "{{ .Values.label }}"
spec:
  schedule: {{ .Values.builder.schedule }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    metadata:
      annotations:
        comet-dxp.com/trigger: "cronjob"
        comet-dxp.com/content-scope: '{{- toJson .Values.contentScope }}'
        comet-dxp.com/label: "{{ .Values.label }}"
      labels:
        comet-dxp.com/builder: "true"
        comet-dxp.com/instance: "{{ .Release.Name }}"
        comet-dxp.com/parent-cron-job: {{ include "comet-site.fullname" . }}-build
        {{- include "comet-site.selectorLabels" . | nindent 8 }}
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 3600
      ttlSecondsAfterFinished: 604800 # 7 days
      template:
        metadata:
          labels:
            {{- range $key, $val := .Values.builder.additionalPodLabels }}
            {{ $key }}: {{ $val | quote }}
            {{- end }}
        spec:
          {{- if .Values.image.pullSecret }}
          imagePullSecrets:
            - name: {{ include "comet-site.fullname" . }}-image-pull-secret
          {{- end }}
          restartPolicy: "Never"
          serviceAccountName: {{ include "comet-site.fullname" . }}
          securityContext:
            {{- toYaml .Values.builder.podSecurityContext | nindent 12 }}
          automountServiceAccountToken: {{ .Values.builder.autoMountServiceAccountToken }}
          containers:
            - name: {{ .Chart.Name }}-build
              securityContext:
                {{- toYaml .Values.builder.securityContext | nindent 16 }}
              {{- if .Values.image.tag }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              {{- else }}
              image: "{{ .Values.image.repository }}@{{ .Values.image.hash }}"
              {{- end }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["bash", "-c"]
              args:
                - set -e;
                  export BUILD_FILE=/tmp/build_$(date +%F_%T).tar;
                  npm run next-build;
                  tar --force-local -cf $BUILD_FILE -C .next .;
                  rsync --remove-source-files $BUILD_FILE /mnt/generated-sites/;
                  rm -f $(ls -1dt /mnt/generated-sites/* | tail -n +3);
                  curl -L https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /tmp/kubectl;
                  chmod u+x /tmp/kubectl;
                  NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace);
                  /tmp/kubectl rollout restart deployment {{ include "comet-site.fullname" . }} -n $NAMESPACE;
              env:
                - name: KUBECTL_VERSION
                  value: "{{ .Values.builder.kubectlVersion }}"
              {{- with .Values.builder.extraEnv }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              envFrom:
                {{- if .Values.env }}
                - configMapRef:
                    name: {{ include "comet-site.fullname" . }}
                {{- end }}
                {{- range $key, $val := .Values.additionalConfigMapNames }}
                - configMapRef:
                    name:  {{ $val }}
                {{- end }}
                {{- if .Values.secrets }}
                - secretRef:
                    name: {{ include "comet-site.fullname" . }}
                {{- end }}
                {{- range $key, $val := .Values.additionalSecretNames }}
                - secretRef:
                    name:  {{ $val }}
                {{- end }}
              volumeMounts:
                - mountPath: /opt/app-root/src/.next
                  name: document-root
                - mountPath: /mnt/generated-sites/
                  name: generated-sites
                - mountPath: /tmp
                  name: tmp
                {{- if .Values.serviceAccount.create }}
                - mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
                  name: "service-account"
                  readOnly: true
                {{- end }}
              resources:
                {{- toYaml .Values.builder.resources | nindent 16 }}
          volumes:
            {{- if .Values.serviceAccount.create }}
            - name: "service-account"
              secret:
                secretName: {{ include "comet-site.fullname" . }}-service-account-token
            {{- end }}
            - name: document-root
              emptyDir: {}
            - name: tmp
              emptyDir: {}
            - name: generated-sites
              persistentVolumeClaim:
{{- if and .Values.pvc.create .Values.pvc.name }}
                claimName: {{ .Values.pvc.name }}
{{- else if .Values.pvc.create }}
                claimName: {{ include "comet-site.fullname" . }}-build
{{- else }}
                claimName: {{ .Values.persistence.existingClaim }}
{{- end }}
{{- end }}
