{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "comet-site.fullname" . }}-main
  labels:
    {{- include "comet-site.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}

spec:
  ingressClassName: nginx
  rules:
  {{if .Values.domains}}
  {{- range .Values.domains }}
  - host: "{{ . }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "comet-site.fullname" $ }}
            port:
              number: 3000
  {{- end }}
  {{- else if .Values.cdn.enabled }}
  - host: "{{ .Values.internalDomain }}"
  {{- else }}
  - host: "{{ .Values.domain }}"
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
          {{- if .Values.prelogin.enabled }}
            name: {{ include "comet-site.fullname" . }}-prelogin
          {{- else }}
            name: {{ include "comet-site.fullname" . }}
          {{- end }}
            port:
              number: 3000

  tls:
  - hosts:
{{- if .Values.domains }}
  {{- range .Values.domains }}
    - "{{ . }}"
  {{- end }}
{{- else if .Values.cdn.enabled }}
    - "{{ .Values.internalDomain }}"
{{- else }}
    - "{{ .Values.domain }}"
{{- end }}
    secretName: {{ include "comet-site.fullname" . }}-main-cert
{{- end }}
