{{- if and (.Values.pvc.create) (.Values.builder.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.pvc.name }}
  name: {{ .Values.pvc.name }}
  {{- else }}
  name: {{ include "comet-site.fullname" . }}-build
  {{- end }}
  labels:
    {{- include "comet-site.labels" . | nindent 4 }}
    {{- toYaml .Values.pvc.additionalLabels | nindent 4 }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
{{- end }}
  resources:
    requests:
      storage: 10Gi
{{- end }}
