{{- if and (.Values.prelogin.enabled) (.Values.prelogin.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comet-site.fullname" . }}-prelogin
  labels:
    {{- include "comet-site.prelogin.labels" . | nindent 8 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.prelogin.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
