{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "comet-site.serviceAccountName" . }}
  labels:
    {{- include "comet-site.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comet-site.fullname" . }}-service-account-token
  annotations:
    kubernetes.io/service-account.name: {{ include "comet-site.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
