{{- range $index, $i := .Values.ingresses }}
  {{ if or (kindIs "string" $i.hostname) (gt (len $i.hostname) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "comet-ingress.fullname" $ }}-{{ $index }}
  labels:
    {{- include "comet-ingress.labels" $ | nindent 4 }}
  annotations:
    {{- range $key, $val := $.Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- if kindIs "slice" $i.hostname }}
      {{- range $k := $i.hostname }}
  - host: {{ $k }}
        {{- if $i.service }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            {{ $i.service | toYaml | nindent 12 }}
        {{- end }}
      {{- end }}
    {{- else }}
  - host: {{ $i.hostname }}
      {{- if $i.service }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            {{ $i.service | toYaml | nindent 12 }}
      {{- end }}
    {{- end }}
    {{- if not (eq $i.tls false) }}
  tls:
      {{- if kindIs "slice" $i.hostname }}
        {{- range $j, $k := $i.hostname }}
    - hosts:
      - {{ $k }}
          {{- if $i.service }}
      secretName: {{ $i.service.name }}-{{ $j }}-cert
          {{- else }}
      secretName: {{ include "comet-ingress.fullname" $ }}-{{ $index }}-{{ $j }}-cert
          {{- end }}
        {{- end }}
      {{- else }}
    - hosts:
      - {{ $i.hostname }}
        {{- if $i.service }}
      secretName: {{ $i.service.name }}-cert
        {{- else }}
      secretName: {{ include "comet-ingress.fullname" $ }}-{{ $index }}-cert
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
