{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "comet-admin.fullname" . }}
  labels:
    {{- include "comet-admin.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  rules:
{{- if .Values.cdn.enabled }}
  - host: "{{ .Values.internalDomain }}"
{{- else }}
  - host: "{{ .Values.domain }}"
{{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "comet-admin.fullname" . }}
            port:
              number: 3000
  tls:
  - hosts:
{{- if .Values.cdn.enabled }}
    - "{{ .Values.internalDomain }}"
{{- else }}
    - "{{ .Values.domain }}"
{{- end }}
    secretName: {{ include "comet-admin.fullname" . }}-cert
{{- end }}
