{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "comet-admin.fullname" . }}
  labels:
    {{- include "comet-admin.labels" . | nindent 4 }}
spec:
{{- if .Values.cdn.enabled }}
  host: "{{ .Values.internalDomain }}"
{{- else }}
  host: "{{ .Values.domain }}"
{{- end }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "comet-admin.fullname" . }}
    weight: 100
{{- end }}
