apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "comet-site-preview.fullname" . }}
  labels:
    {{- include "comet-site-preview.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  TZ: "Europe/Vienna"
  API_URL: https://{{ .Values.api.domain }}{{ .Values.api.basePath }}
  API_URL_INTERNAL: http://{{ .Values.api.internalDomain }}:3000{{ .Values.api.basePath }}
  ADMIN_URL: https://{{ .Values.admin.domain }}
  SITE_URL: https://{{ .Values.domain }}
  SITE_IS_PREVIEW: "true"
  NEXT_PUBLIC_SITE_IS_PREVIEW: "true"
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
