{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "comet-site-preview.fullname" . }}
  labels:
    {{- include "comet-site-preview.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  TZ: "Europe/Vienna"
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
