{{- if (gt (.Values.replicaCount | int) 1) }}
apiVersion: "policy/v1"
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "comet-site-preview.labels" . | nindent 4 }}
  name: {{ include "comet-site-preview.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "comet-site-preview.selectorLabels" . | nindent 6 }}
  minAvailable: 1
{{- end }}