nodeEnv: production
npmRun: serve
timeZone: Europe/Vienna

replicaCount: 1

image:
  repository: nginx
  hash: "" # will be used, if tag is not set
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: "" # will be overwritten by CI

nameOverride: ""
fullnameOverride: ""

domain: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoMountServiceAccountToken: false

service:
  type: ClusterIP
  port: 3000

metrics:
  enabled: false
  containerPorts:
    http: 9466

ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"

route:
  enabled: false
  tls:
    enabled: true

resources:
  limits:
    cpu: 2
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

additionalPodLabels: {}
