name: Create Release Pull Request

on:
    push:
        branches:
            - main

jobs:
    release:
        # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
        # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm install
                  
            - name: Create Release Pull Request
              uses: changesets/action@v1
              with:
                version: npm run changeset:version
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
