{{- if .Values.image.pullSecrets.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imgproxy.imagePullSecrets" . }}
kind: Secret
metadata:
  labels:
    app: {{ template "imgproxy.name" . }}
    chart: {{ template "imgproxy.chart" $ }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    imgproxy: "true"
    {{- range $key, $val := ($.Values.resources.common.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  name: "{{ .Release.Name }}-docker-registry-secret"
type: kubernetes.io/dockerconfigjson
{{- end }}
