{{- if (include "serviceAccount.enabled" $) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "imgproxy.fullname" $ }}-service-account
  labels:
    imgproxy: "true"
    {{- range $key, $val := ($.Values.resources.common.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  annotations:
    {{- with .Values.resources.serviceAccount }}
    {{- if .annotations }}
    {{- .annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- with .Values.features.aws }}
    {{- if and .enabled .iamRoleName }}
    {{ include "aws.iamRoleAnnotation" $ }}
    {{- end }}
    {{- end }}
{{- end }}